services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: carsdb
    volumes:
      - ./mongod.conf:/etc/mongod.conf:ro # Mount the custom configuration file
      - mongo-data:/data/db                   # Persistent data storage
    command: ["mongod", "--config", "/etc/mongod.conf", ] # Specify the configuration file

volumes:
  mongo-data:
    driver: local
